M48
; DRILL file {KiCad (6.0.10-0)} date Monday, January 23, 2023 at 06:28:07 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-23T18:28:07-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X125.73Y-73.025
X125.73Y-112.395
X165.1Y-73.025
X165.1Y-112.395
T0
M30
